### ISSUE TITLE
Typo in documentation breaks example code

### ISSUE THREAD

**Issue by jerrygarciuh** [easy-development/jquery-mt-select#1]
http://demonstration.easy-development.com/jquery-mt-select/documentation/#data-mt-default-values

The examples use  data-mt-default-values-_lang='{"1" : "tag_name"}'

Used as is it does not set values on load.  If  -_lang  is removed the code works and sets default values.

**Comment by robertuniqid** [comment]
oh, you're totally right, my bad. It's was an old example.

I'll update it later on to reflect the good thing.

Cheers,
Robert
